# server
server:
  port: 8888
# MySQL
spring:
  datasource:
    url: jdbc:mysql://172.16.60.16:3306/tvlauncher_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: tvsdk2
    password: tvsdk2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
